### ISSUE TITLE
Add requirements.txt 

### ISSUE THREAD

**Issue by rblcoder** [subhadip-saha-05/Python-Voice-Assistant#24]
Add a requirements.txt for all dependencies

pip install time

pip install pyttsx3

pip install datetime

pip install speechrecognition

pip install wikipedia

pip install webbrowser

pip install random

pip install pyautogui

pip install screen_brightness_control

**Comment by rblcoder** [comment]
Can this be merged?

**Comment by rblcoder** [comment]
@subhadip-saha-05 Anything else needed here? Any queries?

**Comment by subhadip-saha-05** [comment]
Are you a part Of SWOC ? If yes, Then please let me know that you have selected my project or not, give me your details.

**Comment by rblcoder** [comment]
@subhadip-saha-05  I have no idea what SWOC is, if you need this issue and PR deleted I will do so.

**Comment by subhadip-saha-05** [comment]
Actually my this project is selected for an Open Source project Contribution Program named SWOC. If I accept your PR now, everything gonna be messed up. I'll accept and merge that later for sure
