### ISSUE TITLE
Switch Window Command, Take and show screenshot, Tell the IP Adress

### ISSUE THREAD

**Issue by SparklinStar** [subhadip-saha-05/Python-Voice-Assistant#40]
This commands will enhance jarvis. Can you please assign me this issue?

**Comment by v-technoid** [comment]
Can you please assign me this issue to solve?

**Comment by subhadip-saha-05** [comment]
> Can you please assign me this issue to solve?

No only One can solve this issue

**Comment by v-technoid** [comment]
> > Can you please assign me this issue to solve?
> 
> No only One can solve this issue

Okay sure! Thanks!
