### ISSUE TITLE
Feature to find and speak out the dictionary meaning of the word.  **NOT WORKING**

### ISSUE THREAD

**Issue by VishalS-HK** [subhadip-saha-05/Python-Voice-Assistant#45]
This can be achieved using the PyDictionary module.

**Comment by VishalS-HK** [comment]
Could I please be assigned this

**Comment by subhadip-saha-05** [comment]
![image](https://user-images.githubusercontent.com/116567041/211199169-6982d30d-ed88-4f43-b318-d031a907904f.png)
Can you please tell me what to do ?

**Comment by VishalS-HK** [comment]
You will need to `pip install PyDictionary`

**Comment by VishalS-HK** [comment]
<img width="546" alt="image" src="https://user-images.githubusercontent.com/99802796/211201585-257cddb9-8e78-4e5a-9ba6-5e4363b734be.png">

Could you try doing this

**Comment by subhadip-saha-05** [comment]
![image](https://user-images.githubusercontent.com/116567041/211203986-4f515354-6032-4379-9949-ff79f99b558f.png)
See

**Comment by subhadip-saha-05** [comment]
I had verified this with two of my friends, They also said that it's not working...😐😐

**Comment by yash240408** [comment]
This issue has been solved by me, you can close this issue :)

**Comment by subhadip-saha-05** [comment]
make pull request

**Comment by yash240408** [comment]
I have already open the pull request and it's merged also.
I was just informing :)

Regards,
Yash

**Comment by subhadip-saha-05** [comment]
:)
You got some points

**Comment by subhadip-saha-05** [comment]
Idk how the buf fixed
