### ISSUE TITLE
Internet Speed Feature

### ISSUE THREAD

**Issue by v-technoid** [subhadip-saha-05/Python-Voice-Assistant#46]
Using this feature we can make the jarvis speak the internet speed at that instant. Please assign me with this task for SWOC!

**Comment by subhadip-saha-05** [comment]
![image](https://user-images.githubusercontent.com/116567041/211199137-d7e92601-8042-4cbf-b896-432e3a4da569.png)
Solve this First

**Comment by subhadip-saha-05** [comment]
Heyyy, Are you a contributor of SWOC ? If yes, Please kindly Send me your Registered email address and Name

**Comment by v-technoid** [comment]
> Heyyy, Are you a contributor of SWOC ? If yes, Please kindly Send me your Registered email address and Name

Yeah I am Contributor of SWOC.
Name: VISHNUPPRIYAN PL
E-mail ID: vishnutechnophile@gmail.com

**Comment by v-technoid** [comment]
> ![image](https://user-images.githubusercontent.com/116567041/211199137-d7e92601-8042-4cbf-b896-432e3a4da569.png) Solve this First

Yeah I will solve it!

**Comment by v-technoid** [comment]
> > ![image](https://user-images.githubusercontent.com/116567041/211199137-d7e92601-8042-4cbf-b896-432e3a4da569.png) Solve this First
> 
> Yeah I will solve it!

Is this Internet speed feature taken as a contribution for SWOC?

**Comment by subhadip-saha-05** [comment]
> > Heyyy, Are you a contributor of SWOC ? If yes, Please kindly Send me your Registered email address and Name
> 
> Yeah I am a Contributor of SWOC.
> Name: VISHNUPPRIYAN PL
> E-mail ID: vishnutechnophile@gmail.com

Looks Like You haven't applied for SWOC project selection yet 🫥

**Comment by subhadip-saha-05** [comment]
Have you filled that project selection page yet ?

**Comment by v-technoid** [comment]
> 

Oh!

**Comment by v-technoid** [comment]
> Have you filled that project selection page yet ?

Yeah like I haven't, I didn't know that we have something to fill up! Can you guide me through that?

**Comment by v-technoid** [comment]
> > Have you filled that project selection page yet ?
> 
> Yeah like I haven't, I didn't know that we have something to fill up! Can you guide me through that?

**Comment by subhadip-saha-05** [comment]
https://docs.google.com/forms/d/e/1FAIpQLSfpVDPxD2TlgmucZOWsV002w0-CIXaNp8Lx-_1s8suuYkjMHA/viewform
fill this form

**Comment by v-technoid** [comment]
> https://docs.google.com/forms/d/e/1FAIpQLSfpVDPxD2TlgmucZOWsV002w0-CIXaNp8Lx-_1s8suuYkjMHA/viewform fill this form

Thank you!, I have filled this form now!

**Comment by v-technoid** [comment]
Can you include this internet Feature as a SWOC Contribution please?

**Comment by subhadip-saha-05** [comment]
Ok
