### ISSUE TITLE
Display Battery Percentage Feature

### ISSUE THREAD

**Issue by v-technoid** [subhadip-saha-05/Python-Voice-Assistant#47]
This feature can help in displaying the battery percentage by using the voice command in the local System we are in! Please assign me this task for SWOC!

**Comment by subhadip-saha-05** [comment]
Try to do these all small contributions in one pull request

**Comment by v-technoid** [comment]
> Try to do these all small contributions in one pull request

Yeah Okay Sure! Will do it from next time!
