### ISSUE TITLE
Feature of sending mail using jarvis

### ISSUE THREAD

**Issue by Harshit-Raj-14** [subhadip-saha-05/Python-Voice-Assistant#64]
In this, I would like to add a new feature in which we are able to ask the voice assistant to send emails by voice command.

@subhadip-saha-05  kindly look into this issue and please assign me to this I would like to work on this feature

**Comment by PK284** [comment]
@subhadip-saha-05 can you assign me this?
This issue is opened for about 2 months yet unsolved I would like to work on this

**Comment by subhadip-saha-05** [comment]
please do the necesaary changes that I requested in review @Harshit-Raj-14
