### ISSUE TITLE
To add volume up,volume down,mute, and control brightness feature in this project

### ISSUE THREAD

**Issue by pyoushmadan10** [subhadip-saha-05/Python-Voice-Assistant#7]
Please assign this to me if you find it useful

**Comment by subhadip-saha-05** [comment]
Merged !! Nice Job

**Comment by subhadip-saha-05** [comment]
Please recheck that brightness automation portion, it needs debugging.

**Comment by pyoushmadan10** [comment]
> Please recheck that brightness automation portion, it needs debugging.
I checked. It's working fine in my local environment , can you please tell the error?
